# Generated by Django 5.1.4 on 2025-01-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年')),
                ('month', models.IntegerField(verbose_name='月')),
                ('day', models.IntegerField(verbose_name='日')),
                ('food_cost', models.IntegerField(blank=True, null=True, verbose_name='食費')),
                ('fixed_cost', models.IntegerField(blank=True, null=True, verbose_name='固定費')),
            ],
            options={
                'db_table': 'cost_date',
                'constraints': [models.UniqueConstraint(fields=('year', 'month', 'day'), name='unique_cost_date')],
            },
        ),
    ]
